### ISSUE TITLE
Galaxys unbound isn't there.

### ISSUE THREAD

**Issue by Libentho000** [StarCrusher96/Galaxies-Unbound#1]
I downloaded galaxies unbound and dropped it into game data. I enter the tracking station, and I saw no other solar system.

**Comment by BlakeAvery** [comment]
Did you also install kopernicus? Without kopernicus, Galaxies Unbound won't work.

**Comment by Libentho000** [comment]
I did, and I got this message  "Kopernicus was not able to load the custom
planetary system due to an exception in the loading process, loading your
saved game is not recommended, because the missing planets could corrupt
and delete your progress."

**Comment by Libentho000** [comment]
I added Copernicus again today, and I didn't get the loading error.
However, galaxies unbound still didn't work.

**Comment by StarCrusher96** [comment]
Hi there - did you go through the installationguide?
If followed there should be no reason the mod's not working.

**Comment by Libentho000** [comment]
AnimatedDecouplers_v1.4.2
B9partSwitch_v2.10.0
Galaxies-Unbound1.1
Kerbal_Reusability_Expansion-2.8.4
KerbalActuators-1.7.1
Kerbalized_SpaceX
Kopernicus-release1.7.3-1
LoadingscreenManagers
MechJeb2
RetractableLiftingSurface-0.1.6
SpaceX_Launch_Vehicles-5.3
Squad
SquadExpansion
Tundra_Exploration_-_Stocklick_Dragon
Modual Manager

**Comment by StarCrusher96** [comment]
remove SquadExpansion and try again.

**Comment by Libentho000** [comment]
I never found an installation guide.

**Comment by StarCrusher96** [comment]
it's inside the zipfile and added next to the dl's??

**Comment by StarCrusher96** [comment]
https://github.com/StarCrusher96/Galaxies-Unbound/releases/download/1.1/_InstallationGuide.md

**Comment by StarCrusher96** [comment]
Also when you install planet packs it's better to start with them first and add new mods on top of them.

**Comment by Libentho000** [comment]
okay

**Comment by Libentho000** [comment]
Removing squad expansion didn't work.
